config/routes.rb
Rails.application.routes.draw do
  devise_for :patients, path: 'patients'
  #:controllers => { :invitations => 'patients/invitations' }
  devise_for :doctors, path: 'doctors'


  root 'pages#home'

  mount ActionCable.server, at: '/cable'

  resources :doctors, only: ['index', 'show', 'update', 'edit'] do
    resources :documents, only: ['create']
    resources :appointments, only: ['show', 'create']
    resources :doctors_notes, only: ['show']
    resources :chats, only: ['show', 'create'] do
      resources :messages
    end

    member do
      get '/chatroom', to: 'patients#chatroom'
    end
  end

  resources :patients, only: ['index', 'show', 'update', 'edit'] do
    resources :documents, only: ['create']
    resources :appointments, only: ['new', 'create', 'index', 'show'] do
      resources :prescriptions, only: ['show', 'new', 'create'] do
        resources :doses, only: ['new', 'create']
      end
    end

    resources :chats, only: ['show', 'create', 'update'] do
      resources :messages, only: ['show', 'new', 'create']
    end


    member do
      get '/chatroom', to: 'patients#chatroom'
    end
  end

  resources :documents, only: ['destroy']

  resources :prescriptions, only: ['update'] do
    resources :doses, only: ['create', 'delete']
  end

  get '/sign-in', to: 'pages#sign_in', as: 'sign-in'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  post '/dashboard', to: 'pages#invite_patients', as: 'invite'
  get '/settings', to: 'pages#settings', as: 'settings'


  get '/patient', to: 'pages#patient', as: :patient_landing
  get '/doctor', to: 'pages#doctor', as: :doctor_landing

  post '/appointments/:id/accept', to: 'appointments#accept', as: :accept_appointment
  post '/appointments/:id/reject', to: 'appointments#reject', as: :reject_appointment

  post '/chats/:id/accept', to: 'chats#accept', as: :accept_chat
  post '/chats/:id/reject', to: 'chats#reject', as: :reject_chat

  get '/dose/:id', to: 'doses#progress', as: :progress

  get '/medications.json', to: 'medications#index', as: :medications

  get '/appointments/download/:id', to: 'appointments#icalendar', as: :download_calendar

end


# Landing Page
# Dashboard -> Users and Doctors -> Identify which one they are
  # Doctors -> Patients, Conversations
  # Patients -> Doctors, Conversations

app/views/shared/_accepting_invitations.html.erb
<div class="edit_chat">
  <%= "Dr. #{locals[:chat].doctor.first_name} #{locals[:chat].doctor.last_name}" %>
  <div class="buttons">
    <%= button_to accept_chat_path(id: locals[:chat].id), class: 'accept' do %>
      <%= icon('check') %>
    <% end %>
    <%= button_to reject_chat_path(id: locals[:chat].id), class: 'reject' do %>
      <%= icon('times') %>
    <% end %>
  </div>
</div>

app/views/shared/_appointments.html.erb
<!-- This page should list upcoming appointments for patients and it should
allow doctors to accept or reject upcoming appointments.
It receives a @user from the dashboard/conversation -->

<div class="appointments">
  <% if current_class == "doctor" %>
    <h4>Appointment Requests:</h4>
      <ul class="list-group">
        <% if locals[:user].appointments.where(status: "pending").empty? %>
          <li class="list-group-item">You don't have any pending appointments :) </li>
        <% end %>

        <% locals[:user].appointments.where(status: "pending").each do |apt| %>
          <li class="list-group-item">
            <strong><%= apt.patient.first_name %> <%= apt.patient.last_name %></strong> <br>
            <%= apt.date.day %> of  <%= apt.date.strftime("%B") %> - <%= apt.duration %> minutes
            <div class="buttons">
              <%= button_to accept_appointment_path(id: apt.id), class: 'accept' do %>
                <%= icon('check') %>
              <% end %>
              <%= button_to reject_appointment_path(id: apt.id), class: 'reject' do %>
                <%= icon('times') %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>

    <% if !locals[:user].appointments.where(status: "scheduled").empty? %>
      <ul class="list-group">
        <h4>Upcoming Appointments:</h4>
        <% locals[:user].appointments.where(status: "scheduled").each do |apt| %>
          <li class="list-group-item">
            <strong><%= apt.patient.first_name %> <%= apt.patient.last_name %></strong> <br>
            <%= apt.date.day %> of  <%= apt.date.strftime("%B") %> - <%= apt.duration %> minutes
          </li>
            <%= button_to "Add to my calendar", download_calendar_path(id: apt.id), method: :get, class: "btn btn-primary add-to-calendar doctor" %>
        <% end %>
      </ul>
    <% end %>

  <% elsif current_class == "patient" %>
  <h4>Appointment Requests:</h4>
      <ul class="list-group">
        <% if locals[:user].appointments.where(status: "pending").empty? %>
          <li class="list-group-item">You don't have any pending appointments :) </li>
        <% end %>

        <% locals[:user].appointments.where(status: "pending").each do |apt| %>
          <li class="list-group-item">
            <strong><%= apt.patient.first_name %> <%= apt.patient.last_name %></strong> <br>
            <%= apt.date.day %> of  <%= apt.date.strftime("%B") %> - <%= apt.duration %> minutes
          </li>
        <% end %>
      </ul>

  <h4>Upcoming Appointments:</h4>
    <ul class="list-group">
    <% if locals[:user].appointments.where(status: "scheduled").empty? %>
      <li class="list-group-item">You don't have any upcoming appointments :) </li>
    <% end %>
    <% locals[:user].appointments.where(status: "scheduled").each do |apt| %>
      <li class="list-group-item">
        <strong><%= apt.patient.first_name %> <%= apt.patient.last_name %></strong> <br>
        <%= apt.date.day %> of  <%= apt.date.strftime("%B") %> - <%= apt.duration %> minutes
      </li>
    <% end %>
    </ul>


<% if controller_name != "pages" %>
    <%= button_to '#', method: :get, remote: true, 'data-toggle': 'modal', 'data-target': "#appointment-form-#{params[:id]}", class: "btn btn-primary patient", style: "margin-top: 10px" do %>
      Request an Appointment  <%= icon('calendar') %>
    <% end %>
  <% end %>
  <% end %>
</div>

<% if current_class == "patient" && controller_name != "pages" %>
  <%= render 'appointments/new', locals: { user: Doctor.find(params[:id]) } %>
<% end %>

app/views/shared/_card.html.erb
<% if locals[:user].class.to_s == "Patient" %>
<div class="doctor-card">
  <div class="card-avatar">
  <% if locals[:user].avatar.url.nil? %>
    <%= image_tag "https://s3-eu-west-1.amazonaws.com/medi-co/Avatars/Circle#{[0,1,2,3].sample}.png" %>
  <% else %>
    <%= image_tag locals[:user].avatar.url %>
  <% end %>
  <p><%= locals[:user].first_name %> <br><%= locals[:user].last_name %></p>
  </div>
  <div class="card-body">
    <% @apt = locals[:user].appointments.where(doctor_id: current_active.id).where.not(status: "cancelled").where.not(status: "pending").order(:date).last %>
    <% if !@apt.nil? %>
      <% if @apt.status == "scheduled" %>
        <strong>Next Appointment: <%= @apt.date.day.to_s + " " + @apt.date.strftime("%B") %></strong>
      <% elsif @apt.status == "done" %>
        <strong>Last Appointment: <%= @apt.date.day.to_s + " " + @apt.date.strftime("%B") %></strong>
        <p><%= @apt.prescriptions.last.doctors_notes %></p>
      <% end %>
      <% if @apt.prescriptions.last.nil? %>
        No previous prescriptions
      <% else %>
        <% link_to @apt.prescriptions.last do %>
          Previous Prescription
        <% end %>
      <% end %>
    <% else %>
      No previous appointments
    <% end %>

  </div>
  <div class="card-button <%= current_class %>">
    <% if locals[:user].appointments.where(doctor_id: current_doctor.id).empty? %>
      <%= button_to '#', remote:true do %>
        <%= icon('paperclip') %>
      <% end %>
    <% else %>
      <%= button_to new_patient_appointment_prescription_path(patient_id: locals[:user].appointments.where(doctor_id: current_doctor.id).last.patient.id , appointment_id: locals[:user].appointments.where(doctor_id: current_doctor.id).last.id), method: :get do %>
        <%= icon('paperclip') %>
      <% end %>
    <% end %>
    <%= button_to locals[:user], method: :get, form_class: "important" do %>
      <%= icon('paper-plane-o') %>
    <% end %>
    <%= button_to '#', method: :get, remote: true, 'data-toggle': 'modal', 'data-target': "#appointment-form-#{locals[:user].id}" do %>
      <%= icon('calendar') %>
    <% end %>
  </div>
</div>

<!-- DOCTOR SIDE -->
<% else %>

<div class="patient-card">
  <div class="card-avatar">
  <% if locals[:user].avatar.url.nil? %>
    <%= image_tag "https://s3-eu-west-1.amazonaws.com/medi-co/Avatars/Circle#{[0,1,2,3].sample}.png" %>
  <% else %>
    <%= image_tag locals[:user].avatar.url %>
  <% end %>
  <p>Dr. <%= locals[:user].first_name %> <br><%= locals[:user].last_name %> <br> <br><strong><%= Specialty.find(locals[:user].specialty_id).name %></strong></p>
  </div>
  <div class="card-body">
 <% @apt = locals[:user].appointments.where(patient_id: current_active.id).where.not(status: "cancelled").where.not(status: "pending").order(:date).last %>
    <% if !@apt.nil? %>
      <% if @apt.status == "scheduled" %>
        <strong>Next Appointment: <%= @apt.date.day.to_s + " " + @apt.date.strftime("%B") %></strong>
      <% elsif @apt.status == "done" %>
        <strong>Last Appointment: <%= @apt.date.day.to_s + " " + @apt.date.strftime("%B") %></strong>
        <p><%= @apt.prescriptions.last.doctors_notes %></p>
      <% end %>
      <% if @apt.prescriptions.last.nil? %>
        No previous prescriptions
      <% else %>
        <% link_to @apt.prescriptions.last do %>
          Previous Prescription
        <% end %>
      <% end %>
    <% else %>
      No previous appointments
    <% end %>

  </div>
  <div class="card-button <%= current_class %>">
    <% @app = Appointment.where(patient_id: current_active.id, doctor_id: locals[:user].id).last %>
    <% if @app.nil? || @app.prescriptions.empty? %>
      <%= button_to '#', remote:true do %>
        <%= icon('paperclip') %>
      <% end %>
    <% else %>
    <%= button_to patient_appointment_prescription_path(patient_id: current_active.id,
                                                        appointment_id: @app.id,
                                                        id: @app.prescriptions.last.id ), method: :get do %>
      <%= icon('paperclip') %>
    <% end %>
    <% end %>
    <%= button_to locals[:user], method: :get, form_class: "important" do %>
      <%= icon('paper-plane-o') %>
    <% end %>
    <%= button_to '#', method: :get, remote: true, 'data-toggle': 'modal', 'data-target': "#appointment-form-#{locals[:user].id}" do %>
      <%= icon('calendar') %>
    <% end %>
  </div>
</div>
<% end %>

<%= render 'appointments/new', locals: { user: locals[:user] } %>

app/views/shared/_doctor_landing.html.erb
<div id="landing-doc" class="hidden doctor-wrapper">
  <div class="wrapper">

    <div class="card-a" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.1) 50%), url('https://s3-eu-west-1.amazonaws.com/medi-co/Images/iphone-doctor_mockup.jpg');">
      <div class="card-a-box">
        <h3 class="card-a-title">The flexibility to practice<br> medicine anywhere</h3>
        <div class="card-a-text text-center">
          <p>Medi-co lets you connect with patients via secure messaging and document sharing from your mobile device. With Medi-co, you have the flexibility to consult anytime, anywhere -when it’s convenient for you.</p>
        </div>
      </div>
    </div>


    <div class="card-b" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.1) 50%), url('https://s3-eu-west-1.amazonaws.com/medi-co/Images/iphone_patient_mockup.jpg');">
          <div class="card-b-box">
            <h3>A better way to connect with your patients</h3>
            <p>Instantly communicate and share with your patients on our Medi-co chat feature.</p>
            <ul>
              <li>conveniently instant message your patients</li>
              <li>securely and quickly send critical documents
              to your patients</li>
            </ul>
          </div>
     </div>



    <div class="card-c" style= "background-color: white;">
      <div class="card-c-content">
        <h2>A better way to connect with your practice</h2>

        <div class="row" style="align-items: center; display: flex;">
          <div id="reveal1" class="col-xs-12 col-sm-6 benefitsss-icons">
            <%= image_tag('https://s3-eu-west-1.amazonaws.com/medi-co/Icons/schedule_icon+2.png', :width=>110) %>
            <h4>Flexible schedule</h4>
            <p>Consult on your schedule when it’s convenient for you</p>
          </div>
          <div id="reveal2" class="col-xs-12 col-sm-6 benefitsss-icons">
            <%= image_tag('https://s3-eu-west-1.amazonaws.com/medi-co/Icons/practice_icon+2.png', :width=>70) %>
            <h4 style="padding-top: 18px !important;">Grow your practice</h4>
            <p>Attract new patients and eliminate urgent care visits</p>
          </div>
        </div>

        <div class="row">
          <div id="reveal3" class="col-xs-12 col-sm-6 benefitsss-icons">
           <%= image_tag('https://s3-eu-west-1.amazonaws.com/medi-co/Icons/outdoor_icon+2.png', :width=>70) %>
           <h4>Work life balance</h4>
           <p>Free yourself from the office by treating patients virtually</p>
         </div>
         <div id="reveal4" class="col-xs-12 col-sm-6 benefitsss-icons">
          <%= image_tag('https://s3-eu-west-1.amazonaws.com/medi-co/Icons/health_care_icon.png', :width=>70) %>
          <h4>Continuity of care</h4>
          <p>More frequent check-ins with patients online</p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/shared/_dose.html.erb
<%= simple_form_for [@patient, @appointment, @prescription, @dose] do |f| %>
  <%= f.input :days %>
  <%= f.input :frequency %>
  <%= f.input :quantity %>
  <%= f.input :description %>
  <%= f.input :medication_id%>
  <%= f.submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_medication.html.erb
<%= simple_form_for [@medication] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end  %>

app/views/shared/_medication_progress.html.erb
<% @prescription = locals[:prescription] %>
<% if !@prescription.nil? %>
<% @doses = @prescription.doses.order(:medication_id) %>

<ul class="list-group">
  <% @doses.each do |dose| %>
  <% @count = 0 %>
  <% @line_count = 0 %>

  <li class="list-group-item">
  <%= dose.medication.name %>

  <div class="med-progress">
    <% dose.days.times do |days| %>
      <% if ( @line_count / dose.frequency ) > 3 %>
        </div>
        <div class="med-progress">
        <% @line_count = 0 %>
      <% end %>
      <div class="day-pill">
      <span class="day"><%= (dose.created_at + days.days).strftime('%d') %></span>
        <div class="pill">
          <ul>
          <% dose.frequency.times do |fr| %>
              <p hidden id="count"> <%= @count += 1 %></p>
              <% @line_count += 1 %>
            <%= link_to progress_path(id: dose.id, progress: @count), method: :get do %>
              <li class="fr <%= progress_helper(dose, @count) %>">
              </li>
            <% end %>
          <% end %>
        </ul>
        </div>
      </div>


    <% end %>
  </div>
<p style="font-size: 14px;"><strong><%= pluralize(dose.frequency, "time") %></strong> per day for <strong><%= pluralize(dose.days, "day") %></strong></p>
</li>


  <% end %>
<% end %>

app/views/shared/_medications.html.erb
<div class="patient-medication">
  <% current_patient.doses.each do |m| %>
  <p>Name: <%= m.medication.name %></p>
  <p>Duration: <%= m.days %></p>
  <p>Quantity: <%= m.quantity %></p>
  <p>Frequency: <%= m.frequency %> per day</p>
  <p>Instructions: <%= m.description %></p>
  <p><% end %></p>
</div>

app/views/shared/_navbar.html.erb
<div class='navbar-wagon <%= action_name == "home" ? "initial" : "scrolled nav-#{current_class}" %>' id="navbar">

  <% if action_name == "home" %>
    <i class="fa fa-chevron-up fa-4x" id="hamburger-btn"></i>
    <!-- <i class="fa fa-bars fa-2x col-md-12 hidden-md col-lg-12 hidden-lg" id="hamburger-btn"></i> -->
  <% end %>
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <% if (patient_signed_in? or doctor_signed_in?) && action_name != "home" %>
      <%= image_tag "https://s3-eu-west-1.amazonaws.com/medi-co/Logos/logo+whitespace+copywh.png" %>
    <% else %>
      <%= image_tag "https://s3-eu-west-1.amazonaws.com/medi-co/Logos/medi-co.png" %>
    <% end %>
  <% end %>

  <div class="navbar-wagon-right hidden-xs hidden-sm" id="navbar-menu">
    <!-- Right Navigation -->
    <% unless doctor_signed_in? or patient_signed_in? %>
      <div class="navbar-wagon-right hidden-xs hidden-sm <%= action_name == "home" ? 'hidden' : '' %>">
      </div>
    <% end %>

    <% if doctor_signed_in? %>
      <%= link_to 'Dashboard', dashboard_path, class: 'navbar-wagon-item navbar-wagon-link' %>
      <%= link_to t(".sign_out", default: "Logout"), destroy_doctor_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

    <% elsif patient_signed_in? %>
      <%= link_to 'Dashboard', dashboard_path, class: 'navbar-wagon-item navbar-wagon-link' %>
      <%= link_to t(".sign_out", default: "Logout"), destroy_patient_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), sign_in_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

  </div>


  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% if doctor_signed_in? %>
            <li><%= link_to 'Dashboard', dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to t(".sign_out", default: "Logout"), destroy_doctor_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>

          <% elsif patient_signed_in? %>
            <li><%= link_to 'Dashboard', dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to t(".sign_out", default: "Logout"), destroy_patient_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <% else %>
          <!-- Login link (when logged out) -->
            <%= link_to t(".sign_in", default: "Login"), sign_in_path %>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_patient_onboard_modal.html.erb
<button id="modal-click" value="" style="display: none;" data-toggle="modal" data-target="#modalSelector"></button>

<div id="modalSelector" class="modal fade" role="dialog">
 <div class="modal-dialog">

  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Welcome to Medi-co:<br> A Quick Tour</h4>
    </div>
    <div class="modal-body">
      <div id="left" class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3">
        <p>1. Stay on top of your health by checking your profile's medication and wellness updates. </p>
        <%= image_tag('https://s3-eu-west-1.amazonaws.com/medi-co/Icons/med_reminder.png', :width=>151, class: "text-center", id: "modal-image1") %>
      </div>
    </div>
    <div id="center" class="row hidden">
        <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3">
        <p>2. Talk to your doctor and receive essential documents and updates, using Medi-Co's chat feature. </p>
        <%= image_tag('https://s3-eu-west-1.amazonaws.com/medi-co/Icons/smart_phone.png', :width=>127, class: "text-center", id: "modal-image2") %>
      </div>
    </div>
    <div id="right" class="row hidden">
        <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3">
        <p>3. Have more questions or concerns? Book an appointment with your doctor right from  your dashboard! </p>
        <%= image_tag('https://s3-eu-west-1.amazonaws.com/medi-co/Icons/schedule_icon+2.png', :width=>154, class: "text-center", id: "modal-image3") %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <div class="onboard-modal-buttons btn-group" role="group"">
      <button type="button" id="btn-1" class="btn btn-primary">1</button>
      <button type="button" id="btn-2" class="btn btn-primary">2</button>
      <button type="button" id="btn-3" class="btn btn-primary">3</button>
    </div>
  </div>
</div>
</div>

app/views/shared/_patient_profile.html.erb
<div class="patient-profile-information">
  <p><strong>Birthdate</strong>: <%= @patient.birthday %></p>
  <p><strong>Sex:</strong> <%= @patient.sex %></p>
  <p><strong>Bloodtype:</strong> <%= @patient.bloodtype %></p>
  <p><strong>Disability:</strong> <%= @patient.disability %></p>
  <p><strong>Marital Status:</strong> <%= @patient.marital_status %></p>
  <p><strong>Education:</strong> <%= @patient.education %></p>
  <p><strong>Occupation:</strong> <%= @patient.occupation %></p>
  <p><strong>Religion:</strong> <%= @patient.religion %></p>
</div>

app/views/shared/_profile.html.erb
<% if current_class == locals[:user].class.to_s.downcase %>
<div class="profile-dashboard">
  <div class="user-name">
    <div class="user-img">
      <% if locals[:user].avatar.url.nil? %>
        <%= image_tag "https://s3-eu-west-1.amazonaws.com/medi-co/Avatars/Circle1.png" %>
      <% else %>
        <%= image_tag locals[:user].avatar.url %>
      <% end %>
    </div>
  <div class="name">
    <p><%= locals[:user].first_name %> <br><%= locals[:user].last_name %></p>
  </div>
  </div>
  <div class="link-list">
    <ul class="list-group">
      <% if locals[:user].class.to_s == "Doctor" %>
        <a href="invite" data-toggle="modal" data-target="#invite"><li id="<%= current_class %>" class="list-group-item">Invite a Patient</li></a>
      <% else %>
        <a href="update" data-toggle="modal" data-target="#update"><li  id="<%= current_class %>" class="list-group-item"> <%= locals[:user].chats.where(accepted: false).count %> Pending <%= "Invitation".pluralize(locals[:user].chats.where(accepted: false).count) %></li></a>
      <% end %>
      <%= link_to settings_path do %><li class="list-group-item">Settings</li><% end %>
      <a href="#"><li class="list-group-item">Log-out</li></a>
    </ul>
  </div>
</div>

<div id="invite" class="modal fade">
  <h2><%= t "devise.invitations.new.header" %></h2>

  <div>
  <%= simple_form_for(Patient.new, url: invite_path) do |f| %>
  <%= devise_error_messages! %>
  <%= f.text_field :email %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

<div id="update" class="modal fade" role="dialog">
  <div class="modal-dialog apt-form">
      <% if locals[:user].chats.where(accepted: false).count == 0 %>
    <div class="modal-content">
        <div class="no-invitations">
          <%= image_tag "thumbs_up.png", id: "thumbsup" %>
        </div>
    </div>
      <% else %>
    <div class="modal-content" style="padding: 0;">
      <ul class="list-group">
      <% locals[:user].chats.where(accepted: false).each do |chat| %>
        <li class="list-group-item">
        <%= render 'shared/accepting_invitations', locals: { chat: chat } %>
        </li>
      <% end %>
    </ul>
  </div>
    <% end %>
  </div>
</div>

<% else %>
<div class="profile-dashboard">
  <% if current_class == "doctor" %>
    <h6>Your Patient:</h6>
  <% elsif current_class == "patient" %>
    <h6>Your Doctor:</h6>
  <% end %>
  <div class="user-name">
    <div class="user-img">
      <% if locals[:user].avatar.url.nil? %>
        <%= image_tag "https://s3-eu-west-1.amazonaws.com/medi-co/Avatars/Circle1.png" %>
      <% else %>
        <%= image_tag locals[:user].avatar.url %>
      <% end %>
    </div>
  <div class="name">
  <p><%= locals[:user].first_name %> <br><%= locals[:user].last_name %></p>
  </div>
  </div>
  <div class="link-list">
    <ul class="list-group">
      <%= link_to dashboard_path do %><li class="list-group-item">Dashboard</li><% end %>
      <%= link_to settings_path do %><li class="list-group-item">Settings</li><% end %>
      <a href="#"><li class="list-group-item">Log-out</li></a>
    </ul>
  </div>
</div>
<% end %>