config/routes.rb
Rails.application.routes.draw do
  devise_for :patients, path: 'patients'
  #:controllers => { :invitations => 'patients/invitations' }
  devise_for :doctors, path: 'doctors'


  root 'pages#home'

  mount ActionCable.server, at: '/cable'

  resources :doctors, only: ['index', 'show', 'update', 'edit'] do
    resources :documents, only: ['create']
    resources :appointments, only: ['show', 'create']
    resources :doctors_notes, only: ['show']
    resources :chats, only: ['show', 'create'] do
      resources :messages
    end

    member do
      get '/chatroom', to: 'patients#chatroom'
    end
  end

  resources :patients, only: ['index', 'show', 'update', 'edit'] do
    resources :documents, only: ['create']
    resources :appointments, only: ['new', 'create', 'index', 'show'] do
      resources :prescriptions, only: ['show', 'new', 'create'] do
        resources :doses, only: ['new', 'create']
      end
    end

    resources :chats, only: ['show', 'create', 'update'] do
      resources :messages, only: ['show', 'new', 'create']
    end


    member do
      get '/chatroom', to: 'patients#chatroom'
    end
  end

  resources :documents, only: ['destroy']

  resources :prescriptions, only: ['update'] do
    resources :doses, only: ['create', 'delete']
  end

  get '/sign-in', to: 'pages#sign_in', as: 'sign-in'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  post '/dashboard', to: 'pages#invite_patients', as: 'invite'
  get '/settings', to: 'pages#settings', as: 'settings'


  get '/patient', to: 'pages#patient', as: :patient_landing
  get '/doctor', to: 'pages#doctor', as: :doctor_landing

  post '/appointments/:id/accept', to: 'appointments#accept', as: :accept_appointment
  post '/appointments/:id/reject', to: 'appointments#reject', as: :reject_appointment

  post '/chats/:id/accept', to: 'chats#accept', as: :accept_chat
  post '/chats/:id/reject', to: 'chats#reject', as: :reject_chat

  get '/dose/:id', to: 'doses#progress', as: :progress

  get '/medications.json', to: 'medications#index', as: :medications

  get '/appointments/download/:id', to: 'appointments#icalendar', as: :download_calendar

end


# Landing Page
# Dashboard -> Users and Doctors -> Identify which one they are
  # Doctors -> Patients, Conversations
  # Patients -> Doctors, Conversations

app/views/pages/dashboard.html.erb
<div class="dashboard">
  <div class="left-bar">
    <%= render 'shared/profile', locals: { user: @user } %>

    <% if current_class == 'patient' %>
      <div class="medications">
        <h4>Track your medications</h4>
        <%#= render 'shared/medications' %>
        <%= render 'shared/medication_progress', locals: { prescription: current_active.prescriptions.last } %>
      </div>
    <% else %>
      <!-- div class="link-list">
        <ul class="list-group">
          <li class="list-group-item">
            <a href="#">Add a Prescription</a>
          </li>
          <li class="list-group-item">
            <a href="#">Manage your appointments</a>
          </li>
          <li class="list-group-item">
            <a href="#">Search for a Medication</a>
          </li>
       </ul>
      </div> -->
      <%= render 'shared/search_patient' %>
    <% end %>
  </div>

  <% if current_class == 'patient' %>
    <div class="center-bar">
      <div class="center">
        <div class="dash-main <%= current_class %>">
           <div class="past">
          <% if @user.appointments.where(status: "done").last.nil? %>
          You didn't have a past appointment
          <% else %>
          <% @last = @user.appointments.where(status: "done").last %>
          <h4>Last Appointment: <%= @last.doctor.first_name %> <%= @last.doctor.last_name %></h4>
          <hr>
          <%= @last.date.day %> of <%= @last.date.strftime("%B") %>
          <% end %>
        </div>
        <div class="upcoming">
          <% if @user.appointments.where(status: "scheduled").empty? %>
            You don't have a scheduled appointment
          <% else %>
          <% @next = @user.appointments.where(status: "scheduled").first %>
          <h4>Next Appointment: <%= @next.doctor.first_name %> <%= @next.doctor.last_name %></h4>
          <hr>
          <%= @next.date.day %> of <%= @next.date.strftime("%B") %> at <%= @next.date.strftime('%k') %>:<%= @next.date.strftime('%M') %>
          <% end %>
        </div>
        </div>
          <div class="dash-card"  style="padding: 20px 40px 10px 30px;">
            <% if @card_array.empty? %>
              <div class="card-img">
              <%= image_tag "https://s3-eu-west-1.amazonaws.com/medi-co/Images/no_doctors.png", style: "width: auto; height: 300px;" %>
              </div>
            <% end %>
           <ul class="list-group">
             <% @card_array.each do |chat| %>
             <li class="list-group-item">
               <%= render 'shared/card', locals: { user: chat.doctor } %>
             </li>
             <% end %>
           </ul>
          </div>
    </div>
  </div>
  <div class="right-bar">
    <div class="appo-dash">
      <%= render 'shared/appointments', locals: { user: @user } %>
    </div>
    <div class="documents-patient">
      <%= render 'shared/documents', locals: { user: @user } %>
    </div>
  </div>

  <% elsif current_class == "doctor" %>
  <div class="center-bar">
    <div class="center">
      <div class="dash-main <%= current_class %>">
        <div class="past">
          <% if @user.appointments.where(status: "done").last.nil? %>
          You didn't have a past appointment
          <% else %>
          <% @last = @user.appointments.where(status: "done").last %>
          <h4>Last Appointment: <%= @last.patient.first_name %> <%= @last.patient.last_name %></h4>
          <%= @last.date.day %> of <%= @last.date.strftime("%B") %>
          <hr>
          <p>"<emphasis><%= @last.prescriptions.last.doctors_notes %></emphasis>"</p>
          <%= button_to "Edit Prescription",
          new_patient_appointment_prescription_path(patient_id: @last.patient, appointment_id: @last),
           method: :get,
           class: "btn btn-white",
           style: 'color: #ff686b; margin-top: 10px;' %>
          <% end %>
        </div>
        <div class="upcoming">
          <% if @user.appointments.where(status: "scheduled").empty? %>
          You don't have a scheduled appointment
          <% else %>
          <% @next = @user.appointments.where(status: "scheduled").first %>
          <h4>Next Appointment: <%= @next.patient.first_name %> <%= @next.patient.last_name %></h4>
          <hr>
          <%= @next.date.day %> of <%= @next.date.strftime("%B") %> at <%= @next.date.strftime('%k') %>:<%= @next.date.strftime('%M') %>
          <%= button_to "End Appointment",
          new_patient_appointment_prescription_path(patient_id: @next.patient, appointment_id: @next),
           method: :get,
           class: "btn btn-white",
           style: 'color: #ff686b; margin-top: 10px;' %>
          <% end %>
        </div>
      </div>
      <div class="dash-card" style="padding: 20px 40px 10px 30px;">
          <% if @card_array.empty? %>
            <div class="card-img">
              <%= image_tag "https://s3-eu-west-1.amazonaws.com/medi-co/Images/no_patients.png", style: "width: auto; height: 300px;" %>
            </div>
          <% end %>
        <ul class="list-group">
          <% @card_array.each do |chat| %>
          <li class="list-group-item">
            <%= render 'shared/card', locals: { user: chat.patient } %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="right-bar">
    <div class="appo-dash">
      <%= render 'shared/appointments', locals: { user: @user } %>
    </div>
    <div class="documents-patient">
      <%= render 'shared/documents', locals: { user: @user } %>
    </div>
  <% end %>
</div>



<%= content_for :title do %>
  <%= "Dashboard - Medi-co" %>
<% end %>

app/views/pages/home.html.erb
<%= render 'shared/home_banner' %>
<%= render 'shared/doctor_landing' %>
<%= render 'shared/patient_landing' %>
<%= render 'shared/footer' %>

<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>



<% content_for(:js_content) do %>
<script>
  const btnDoctor = document.getElementById("btn-home-doctor");
  const landingDoc = document.getElementById("landing-doc");
  const btnPatient = document.getElementById("btn-home-patient");
  const landingPatient = document.getElementById("landing-patient");

  const mq = window.matchMedia( "(max-width: 415px)" );
  const nav = document.getElementById("navbar");
  const menu = document.getElementById("navbar-menu");
  const navBtn = document.getElementById("hamburger-btn");
  if (mq.matches) {
console.log(mq.matches);
    nav.classList.add("scrolled");
    nav.classList.remove("initial");
    navBtn.style.display="none";
  } else {
    const lastScrollTop = 0;

    window.addEventListener("scroll", function(){
     const st = window.pageYOffset || document.documentElement.scrollTop;
     console.log(st);

     if (st > lastScrollTop){
      nav.classList.add("scrolled");
      nav.classList.remove("initial");
      menu.classList.remove("hidden");
      // hide burger
      nav.querySelector("i").classList.add('hidden');
     } else {
      nav.classList.add("initial");
      nav.classList.remove("scrolled");
      menu.classList.add("hidden");
      nav.querySelector("i").classList.remove('hidden');
     };
    //lastScrollTop = st;
    }, false);

    navBtn.addEventListener("click", () => {
      nav.classList.add("scrolled");
      nav.classList.remove("initial");
      menu.classList.remove("hidden");
      navBtn.classList.add("hidden");
    });
  }

  function visitedButton1()
  {
    document.getElementById('btn-home-doctor').setAttribute("class", "style1");
  }
  function visitedButton2()
  {
    document.getElementById('btn-home-patient').setAttribute("class", "style1");
  }

  btnDoctor.addEventListener("click", () => {
    landingPatient.classList.add("hidden");
    landingDoc.classList.remove("hidden");
    landingDoc.scrollIntoView({behavior: "smooth", block: "start"});
    visitedButton1();
  });

  btnPatient.addEventListener("click", () => {
    landingDoc.classList.add("hidden");
    landingPatient.classList.remove("hidden");
    landingPatient.scrollIntoView({behavior: "smooth", block: "start"});
    visitedButton2();
  });

  window.sr = ScrollReveal({opacity: 0.1, distance: '40px', viewFactor: 0.7,});
  sr.reveal('.card-a-box', {opacity: 0.1, distance: '40px', viewFactor: 0.4, rotate: { x: -50, y: 0, z: 0 }})
  sr.reveal('.card-b-box', {opacity: 0.1, distance: '40px', viewFactor: 0.4, rotate: { x: -50, y: 0, z: 0 }})
  sr.reveal('.card_one_box', {opacity: 0.1, distance: '40px', viewFactor: 0.4, rotate: { x: -50, y: 0, z: 0 }})
  sr.reveal('.card_two_box', {opacity: 0.1, distance: '40px', viewFactor: 0.4, rotate: { x: -50, y: 0, z: 0 }})
  sr.reveal('.card-three-content', {opacity: 0.1, distance: '40px', viewFactor: 0.4, rotate: { x: -50, y: 0, z: 0 }})
  sr.reveal('#reveal1', {opacity: 0.1, distance: '40px', viewFactor: 0.7,});
  sr.reveal('#reveal2', {opacity: 0.1, distance: '40px', viewFactor: 0.7,});
  sr.reveal('#reveal3', {opacity: 0.1, distance: '40px', viewFactor: 0.7,});
  sr.reveal('#reveal4', {opacity: 0.1, distance: '40px', viewFactor: 0.7,});

</script>
<% end %>

app/views/pages/settings.html.erb
<div class="container">

  <h1>Settings</h1>
  <%= simple_form_for(@user) do |f| %>
  <%= f.input :email %>
  <%= f.input :avatar %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= @specialties %>
  <% if current_class == "doctor" %>
  <%= f.input :specialty_id, collection: Specialty.all.order(:name).collect { |i| [i.name, i.id] }, include_blank: true %>
  <% else %>
  <div class="flex-on">
    <div style="width: 50%; border-right: 1px solid #84dcc6; padding: 10px 20px;">
      <strong>Sex</strong>
      <%= f.input :sex, label: false, collection: ['Male', 'Female', 'Other'], as: :radio_buttons, input_class: "form-check-input"  %>
      <strong>Bloodtype</strong>
      <%= f.input :bloodtype, label: false,collection: ['A', 'B', 'O', 'AB'], as: :radio_buttons, input_class: "form-check-input"  %>
      <strong>Education</strong>
      <%= f.input :education, label: false, collection: ['Basic Education', 'High School', 'College', 'Other'], as: :radio_buttons, input_class: "form-check-input" %>
    </div>
    <div style="width: 50%; padding: 10px 20px;">
      <strong>Marital Status</strong>
      <%= f.input :marital_status, label: false, collection: ['Married', 'Single', 'Other'], as: :radio_buttons, input_class: "form-check-input"  %>
      <strong>Occupation</strong>
      <%= f.input :occupation, label: false, collection: ['Retired', 'Full-time job', 'Student', 'Not working', 'Other'], as: :radio_buttons, input_class: "form-check-input"  %>
    </div>
  </div>
  <%= f.input :disability %>
  <% end %>
  <%= f.submit "Update Information", class: 'btn btn-primary' %>
  <% end %>

  <% if current_active.sign_in_count == 1 && current_class == "patient" %>
    <%= render 'shared/patient_onboard_modal' %>
  <% elsif current_active.sign_in_count == 1 && current_class == "doctor"%>
    <%= render 'shared/doctor_onboard_modal' %>
  <% end %>

</div>
<% content_for :js_content do %>
  <script>
    $(document).ready(function() {
      $('#modal-click').click();
    });

    <% if current_active.sign_in_count == 1 && current_class == "patient" %>

      const btn1 = document.getElementById('btn-1');
      const btn2 = document.getElementById('btn-2');
      const btn3 = document.getElementById('btn-3');
      console.log(btn1);

      btn1.addEventListener('click', function(e) {
        e.preventDefault();
        document.getElementById('left').classList.remove('hidden');
        document.getElementById('center').classList.add('hidden');
        document.getElementById('right').classList.add('hidden');
      });
      btn2.addEventListener('click', function(e) {
        e.preventDefault();
        document.getElementById('center').classList.remove('hidden');
        document.getElementById('left').classList.add('hidden');
        document.getElementById('right').classList.add('hidden');
      });
      btn3.addEventListener('click', function(e) {
        e.preventDefault();
        document.getElementById('right').classList.remove('hidden');
        document.getElementById('center').classList.add('hidden');
        document.getElementById('left').classList.add('hidden');
      });
    <% else %>
     const btnOne = document.getElementById('btn-one');
     const btnTwo = document.getElementById('btn-two');
     const btnThree = document.getElementById('btn-three');

     const docLeft = document.getElementById('doc-left');
     const docCenter = document.getElementById('doc-center');
     const docRight = document.getElementById('doc-right');
     console.log(btnTwo);

     btnOne.addEventListener('click', function(e) {
      e.preventDefault();
      docLeft.classList.remove('hidden');
      docCenter.classList.add('hidden');
      docRight.classList.add('hidden');
      });

      btnTwo.addEventListener('click', function(e) {
        e.preventDefault();
        docCenter.classList.remove('hidden');
        docLeft.classList.add('hidden');
        docRight.classList.add('hidden');
      });

      btnThree.addEventListener('click', function(e) {
        e.preventDefault();
        docRight.classList.remove('hidden');
        docCenter.classList.add('hidden');
        docLeft.classList.add('hidden');
      });

    <% end %>
  </script>
<% end %>

<%= content_for :title do %>
  Settings
<% end %>

app/views/pages/sign_in.html.erb
<div class="sign-in-form">
  <div id="login-buttons">
    <div>
      <h2>You are a:</h2>
    </div>
    <ul class="list list-inline" id="question">
      <a href="#" class= "btn btn-primary btn-lg" id="doctor" data-toggle="modal" data-target="#doctormodal"> Doctor </a>
      <a href="#"" class= "btn btn-success btn-lg" id= "patient" data-toggle="modal" data-target="#patientmodal"> Patient</a>
    </ul>
  </div>
</div>
<div class="login">
<% @resources.each do |resource| %>
<div class="modal fade" id="<%= resource.to_s %>modal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <ul class="nav nav-tabs">
          <li class="active"><a  data-toggle="tab" href="#<%= resource.to_s %>login">Sign In</a></li>
          <li><a data-toggle="tab" href="#<%= resource.to_s %>signup">New Account</a></li>
        </ul>
<!--         <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
 -->      </div>

      <div class="modal-body">
        <div class="tab-content">

          <div id="<%= resource.to_s %>login" class="tab-pane fade in active">
       <!--      <h3>Login here</h3> -->
            <%= simple_form_for(resource, :url => session_path(resource)) do |f| %>
            <%= f.text_field :email, placeholder: "E-mail", class: 'text-field', :size => 39 %>
            <p></p>
            <%= f.password_field :password, placeholder: "Password", class: 'text-field', :size => 39 %>
            <p></p>
            <%= f.input :remember_me, as: :boolean, class: "accept" %>
            <div class="buttons">
              <%= f.submit 'Log-in', class: 'btn patient', :size => 39  %>
            </div>
              <p><%= link_to "Forgot your password?", new_password_path(resource), class: "forgot" %></p>
            <% end %>
          </div>


          <div id="<%= resource.to_s %>signup" class="tab-pane fade">
   <!--          <h3>Signup here</h3> -->
            <%= simple_form_for(resource, :url => registration_path(resource)) do |f| %>
            <%= f.text_field :email, placeholder: "E-mail", class: 'text-field' , :size => 39 %>
            <p></p>
            <p></p>
            <%= f.password_field :password, placeholder: "Password", class: 'text-field' , :size => 39  %>
            <p></p>
            <p></p>
            <%= f.password_field :password, placeholder: "Confirm password", class: 'text-field', :size => 39  %>
            <div class="buttons">
              <%= f.submit 'Sign up', class: 'btn patient', :size => 39 %>
            </div>

            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>


</div>